/** @type {import('tailwindcss').Config} */
// Design tokens. The website must feel peaceful, divine, elegant, premium,
// spiritual, emotionally calming. Inspired by Japanese minimalism, Apple HIG,
// Material simplicity, and Indian temple aesthetics.
//
// All colors are exposed as Tailwind utilities (e.g. `bg-cream-50`,
// `text-saffron-600`, `border-maroon-700`) and CSS custom properties in
// `src/styles/tokens.css`. Keep both in sync.
/**
 * Theme strategy — class-based dark mode.
 *
 * `darkMode: 'class'` flips a `.dark` class on <html> to drive every
 * dark-mode variant. All Tailwind colors are exposed as utility names
 * (e.g. `bg-cream-50`, `text-saffron-600`) with both light and dark
 * values; components opt into dark variants via `dark:` prefixes. The
 * CSS-variable equivalents in `src/styles/tokens.css` mirror this — the
 * ThemeProvider flips `.dark` on <html>, which swaps the custom
 * properties for hard-coded rgba values used by Framer Motion + SVG +
 * inline gradients that can't read Tailwind utilities.
 *
 * Brand philosophy: light mode is "morning darshan, soft sunlight,
 * cream walls, open space" and dark mode is "evening arati, deep blue
 * sky, gentle lamp light, quiet atmosphere". The two moods are
 * deliberately different rather than inversions of each other — see
 * tokens.css for the design intent.
 */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '1.25rem',
        sm: '1.5rem',
        lg: '2rem',
        xl: '2.5rem',
      },
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1200px',
        '2xl': '1320px',
      },
    },
    extend: {
      colors: {
        // Cream — warm-paper surfaces for light mode. Dark mode
        // surfaces pull from `ink-*` and `plum-dark` instead; cream is
        // not used as a background in dark mode (the mood is "evening
        // temple", not "white-on-black").
        cream: {
          50: '#FBF7F0',
          100: '#F5EFE3',
          200: '#EDE3CE',
          300: '#E0D2B3',
        },
        // New for v0.2 — warm-beige atmosphere
        beige: {
          50: '#F7F0E2',
          100: '#EFE6D2',
        },
        // New for v0.2 — pure-cream atmosphere (almost white, still warm)
        'pure-cream': '#FEFBF5',
        temple: {
          400: '#B08664',
          500: '#8E6849',
          600: '#6E4F36',
          700: '#4E3825',
          800: '#2E2118',
        },
        // Saffron — accent gold. In dark mode these same hues glow
        // brighter (lighter + warmer 400/300 tones) with text-shadow
        // applied via the .glow-gold utility — never a flat fill.
        saffron: {
          300: '#F1B96B',
          400: '#E5A24A',
          500: '#D98A2B',
          600: '#B86E1e',
          // 700 — WCAG-compliant small-text saffron (≥4.5:1 on cream-50).
          // Used for `.eyebrow` labels and inline timestamps so they don't
          // fall under the 4.5:1 body-text threshold at 11–14px.
          '700': '#9C5712',
          'gold-dark': '#E0AA4C',
        },
        peacock: {
          500: '#1B5E7A',
          600: '#134A60',
          700: '#0D3A4C',
          // Dark-mode peacock — the "evening sky" wash behind
          // important sections. Deep, not bright.
          'dark': '#0B2533',
          'deep': '#091823',
        },
        maroon: {
          600: '#7A1F2B',
          700: '#5C1620',
          800: '#3F0E16',
          // Dark-mode plum — used for altar/cardinal accent.
          'plum-dark': '#2A0A12',
        },
        ink: {
          900: '#15131A',
          800: '#1E1A24',
          700: '#27212E',
          // New dark palette — page/section/card/floating hierarchy.
          // Each layer sits one notch lighter than the previous so
          // surfaces feel like they're floating at different depths.
          'page': '#0F0D13',         // outermost page
          'page-2': '#11101A',       // alt page rhythm
          'section': '#141118',      // raised section
          // `section-2` — alias for `charcoal` (mid-elevation ink). Defined
          // here so references like `bg-ink-section-2` / `dark:bg-ink-section-2`
          // actually get generated by Tailwind's purge. Charcoal is the same
          // value and remains the canonical name; this matches the CSS custom
          // property `--bg-section-2` in src/styles/tokens.css.
          'section-2': '#18151D',
          'charcoal': '#18151D',     // mid-elevation section
          'card': '#1A1720',         // card surface
          'floating': '#211C29',     // floating card / dialog
          'lift': '#26212F',         // hover state on floating
          'border': '#2A2433',       // visible borders on dark
        },
        // Dark-mode fg tones — never #FFFFFF, always warm cream.
        // v0.8: muted lifted #AAA29B → #BFB8AE so it clears WCAG AA
        // 4.5:1 against ink-floating (#211C29) when used at 100%
        // opacity. Old value measured ~4.1:1 which failed at body sizes.
        // `muted-2` lifted similarly so 3-level hierarchy still has
        // visible step-down without violating contrast on cards.
        'fg': {
          main: '#F2EEE7',
          body: '#DCD6CC',
          muted: '#BFB8AE',
          'muted-2': '#9C948B',
          accent: '#E0AA4C',
        },
        // Lamp glow — radial-gradient targets for the dark-mode
        // "oil-lamp warmth" atmosphere behind important sections.
        'lamp': {
          warm: '#D2963C',
          amber: '#A66A1F',
          'oil': '#C8884F',
        },
      },
      fontFamily: {
        display: ['Fraunces', 'ui-serif', 'Georgia', 'serif'],
        sans: ['"Work Sans"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
        serifBn: ['"Tiro Bangla"', 'Noto Serif Bengali', 'Fraunces', 'serif'],
        handwriting: ['"Pinyon Script"', '"Allura"', '"Dancing Script"', 'cursive'],
      },
      fontSize: {
        'display-xl': ['clamp(3rem, 7vw, 5.5rem)', { lineHeight: '0.92', letterSpacing: '-0.025em' }],
        'display-lg': ['clamp(2.5rem, 5vw, 4rem)', { lineHeight: '1.02', letterSpacing: '-0.02em' }],
        'display-md': ['clamp(1.75rem, 3vw, 2.5rem)', { lineHeight: '1.1', letterSpacing: '-0.01em' }],
        // New for v0.2 — editorial-size quotes
        'quote': ['clamp(2.25rem, 5vw, 4.25rem)', { lineHeight: '1.12', letterSpacing: '-0.02em' }],
      },
      letterSpacing: {
        eyebrow: '0.18em',
      },
      maxWidth: {
        prose: '68ch',
        editorial: '52ch',
      },
      // New for v0.2 — full soft-shadow scale
      boxShadow: {
        soft: '0 1px 2px rgba(20,16,24,0.04), 0 8px 24px rgba(20,16,24,0.06)',
        lift: '0 2px 4px rgba(20,16,24,0.05), 0 16px 40px rgba(20,16,24,0.08)',
        temple: '0 4px 8px rgba(20,16,24,0.06), 0 24px 56px rgba(20,16,24,0.10)',
        saffron: '0 8px 28px rgba(217,138,43,0.22)',
        // Hero-scale shadow used on cards that need to lift dramatically
        // against a dark page. Saffron glow stays in the mix so the
        // shadow reads as "lit by oil lamps" rather than just black.
        'temple-deep': '0 25px 60px rgba(0,0,0,0.55), 0 0 30px rgba(224,170,76,0.15)',
        // Inner highlight used on glass surfaces
        'inset-top-light': 'inset 0 1px 0 rgba(255,255,255,0.6)',
      },
      borderRadius: {
        xl2: '1.25rem',
        // New for v0.2
        '2xl2': '2.5rem',
        'editorial': '1.75rem',
      },
      // New for v0.2 — backdrop blur scale
      backdropBlur: {
        xs: '2px',
        glass: '14px',
      },
      transitionTimingFunction: {
        divine: 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
      transitionDuration: {
        450: '450ms',
        700: '700ms',
        900: '900ms',
      },
      keyframes: {
        ticker: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        glow: {
          '0%, 100%': { opacity: '0.55' },
          '50%': { opacity: '0.9' },
        },
        // New for v0.2 — slow, ambient radial-light drift
        'ambient-drift': {
          '0%, 100%': { transform: 'translate3d(0,0,0) scale(1)' },
          '50%': { transform: 'translate3d(2%, -1%, 0) scale(1.05)' },
        },
        // Subtle vertical breathing used inside editorial images
        'breathe': {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.02)' },
        },
      },
      animation: {
        ticker: 'ticker 60s linear infinite',
        'fade-up': 'fade-up 0.7s cubic-bezier(0.22, 1, 0.36, 1) both',
        glow: 'glow 4s ease-in-out infinite',
        'ambient-drift': 'ambient-drift 18s ease-in-out infinite',
        'breathe': 'breathe 12s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
